name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  # 1) Generar dist/ y subirlo COMO artifact para Pages
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build production files
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # <-- Aquí debe ir upload-pages-artifact@v1, ¡no upload-artifact@v3!
      - name: Upload dist/ to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  # 2) Bajar ese mismo artifact y publicarlo
  deploy:
    needs: build_and_upload
    runs-on: ubuntu-latest

    steps:
      - name: Download Pages artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
